### PR TITLE
Enables listening on IPv6

### PR DESCRIPTION
**Pull request by voqelfre1**
Fixes timeout when a dns aaaa entry exists for the domain. Does not break with the installer setting tcp.

### CODE REVIEW

**Comment by orazioedoardo** [comment]
Can you elaborate a bit more?

**Comment by voqeIfrei** [comment]
On my installations ive always had the issue that when i have the v6 address of the server in the dns record, that my clients (Linux and iOS) always try to connect to the v6 address on which the openvpn server does not listen, thus the connection attempt will time out. 
This line enables listening on v6. 
(The installer replaces udp with tcp, so that works.)
In addition, when ufw is installed the openvpn port will be opened on v4 and v6, so that does not require addidional modification.

**Comment by 4s3ti** [comment]
Just adding udp6 by default to all configs does not seem right.  
Like this the server is going to listen on udp6 either you want it or not. 

This should be customizable, 
Script should detect for IPv6
prompt if user wants to listen on it or not.

**Comment by TinCanTech** [comment]
> Just adding udp6 by default to all configs does not seem right.
> Like this the server is going to listen on udp6 either you want it or not.

If the server device is not configured with IPv6 then this change will cause FATAL errors.

**Comment by voqeIfrei** [comment]
Makes sense, but when asking the user it should be fine, right?

**Comment by 4s3ti** [comment]
@voqeIfrei that is just not enought ... wee need to see the bigger picture and add some common sense to it, who is the target of PiVPN? who are the main users? 

 There is much more to worry about. , just asking its not okay ... Most people will answer without even knowing what they are answering to, and then what will happen? flood of issues and questions that could be avoided. 

We try to provide something that is both simple and secure enough to use, when you setup a VPN with PiVPN you don't just get default settings. 

Another issue is ...  Most of us don't have a way to test that, not even sure if it can be tested also with automated testing, which i will be working on during the next couple of weeks, this said, even tough i'd really like to ...  i don't think it is something it is safe to add, unless there is someone with the ability to test IPv6, willing to hang around and not vanish. I might have the ability to test it however ... i lack the time so i cannot risk becoming a bottleneck for the project itself. 

if you wanna add support for IPv6, and stick around to help maintaining it, here is a thread to read about it: https://github.com/pivpn/pivpn/issues/259  I'd also recommend you reading the code to understand all that is done for IPv4 and replicate it to IPv6

**Comment by MichaIng** [comment]
Just to throw in a test whether IPv6 is enabled and a default route exists on the server: `[[ $(ip -6 r l ::/0) ]]`
It does not assure that real internet connectivity via IPv6 is possible (a ping would be required for that), but if this is not the case, the result will be just the same as it is now: connection timeout

Luckily, IPv6 requests of the clients time out instead of bypass the VPN. In case of WireGuard, if IPv6 is not explicitly part of the client configs `AllowedIPs`, those will simply bypass the VPN, in the worst case unrecognised by the user.

**Pull request closed without merging**
