### PR TITLE
Added script to easily update the crl

### PR DESCRIPTION
**Pull request by sqrtroot**
As stated in issues such as #567 people are running into the issue that their crl expires.
This script adds an easy way to update this list.

### CODE REVIEW

**Comment by sqrtroot** [comment]
Seems like test was not up to date with the master branch, should we merge into that or go straight to master?

**Comment by 4s3ti** [comment]
From Now On No Commit should go straight into master, unless its something really important or changes into Readme or documentation. 
Regardless, untill everything is clean and tidy i thing we should not approve any commits. 
want to avoid things breaking and not working.

**Comment by sqrtroot** [comment]
I agree on not committing to master (you can enforce this in the repo settings).
Unfortunately test was lacking behind master so there are now commits in this pr that are not part of it, oh well :)

**Comment by 4s3ti** [comment]
when i finish cleaning up Test should be ok. 
Jusg hang on a couple of weeks pls =)

**Comment by 4s3ti** [comment]
to avoid Messups... 
I will be closing the PRs for now. 

I will be fixing both test and master branch want to avoid further issues. 
Please Open a new PR to test branch once I have finished getting it done.

**Comment by 4s3ti** [comment]
@sqrtroot go ahead, sync your fork with pivpn, and make a new pull request to test branch please.

**Pull request closed without merging**
