### PR TITLE
Merge test

### PR DESCRIPTION
**Pull request by orazioedoardo**
Main changes:
- More validation of user input
- Check if package installation is successful
- Detect netmask when setting a static IP
- Avoid adding repositories if they already exist
- Switch DH params from 2ton.com.au to RFC 7919
- Using 'install' to copy files into place
- Move the self check to a different script and use it for both OpenVPN and WireGuard
- Add 'pivpn -wg' to update WireGuard on older Raspberry Pis

@4s3ti do you approve this merge?

### CODE REVIEW

**Comment by 4s3ti** [comment]
Done! =)

**Comment by orazioedoardo** [comment]
Mmmmh, how did you merge the pull request? I don't see the commit history originally from test.

**Comment by 4s3ti** [comment]
@orazioedoardo .... I squashed some commits .. that might be why.

**Comment by orazioedoardo** [comment]
I think having commits is more useful, I would revert and merge normally. Now test is out of date too.

**Comment by 4s3ti** [comment]
Yeah .. that squash was bit unintentional ... lets revert and make it again i won't squash this time =p

**Comment by 4s3ti** [comment]
check this one: https://github.com/pivpn/pivpn/tree/revert-929-test

if it looks good .. if so let me know and i merge it

**Comment by orazioedoardo** [comment]
@4s3ti Looks good, all commits are there and if I compare with master there are no changes as expected.

**Comment by 4s3ti** [comment]
Done .. hope its ok now.

**Pull request merged**
