### PR TITLE
Assigning static IP for clients

### PR DESCRIPTION
**Pull request by anudeepND**
Added information about how to assign static IP for .ovpn clients.

### CODE REVIEW

**Comment by cfcolaco** [comment]
Thanks @anudeepND, very useful however I am not going to merge, 

Will put that info on the Wiki instead, think it is a better place to have this kind of info.

Going to leave the PR Open until I have a bit more time for that. 

Thanks a lot once again! =)

**Comment by redfast00** [comment]
@anudeepND I don't know if you can edit the wiki, but if you can, you can just copy-paste what you wrote, since it's also Markdown. If not, ping me and I'll put it in.

**Comment by cfcolaco** [comment]
@redfast00 Nope the wiki can only be edited by us. =/

**Comment by anudeepND** [comment]
@cfcolaco and @redfast00  you can close this PR once it's included in the Wiki, thanks for providing this great tool :)

**Comment by redfast00** [comment]
@anudeepND I just put it in the wiki. Thank you!

**Pull request closed without merging**
