### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by NajmAjmal**
Added extra ! mark

### CODE REVIEW

**Comment by 4s3ti** [comment]
Curious .... Why an extra mark? what difference does it really make or what exactly does it mean?  

Sure i could google it, but more interested in your take :D

**Comment by 4s3ti** [comment]
Merged anyway as to me it doesn't really matter, but I'm still curious about it :)

**Comment by NajmAjmal** [comment]
In informal writing, multiple exclamation points are sometimes used to indicate **stronger emphasis or emotion.**

**Comment by 4s3ti** [comment]
That does not answer my question. You changed from 2  !! to !!! what difference does it make??

**Pull request merged**
