### PR TITLE
add Wireguard MTU support via setupVARS.conf

### PR DESCRIPTION
**Pull request by DerDanilo**
Adding Wireguard MTU support to fix https://github.com/pivpn/pivpn/issues/1019

### CODE REVIEW

**Review by 4s3ti — COMMENTED** [review]
LGTM .. will leave this for @orazioedoardo to take a second look as well

**Comment by orazioedoardo** [comment]
Switch target branch to test please.

**Comment by DerDanilo** [comment]
> 
> 
> Switch target branch to test please.

Done

**Comment by DerDanilo** [comment]
How do we get this merged now? Using my patch in several installations and it's working fine.

**Pull request merged**
