### PR TITLE
Support setupVars for pivpnNET, subnetClass and ALLOWED_IPS via unattended setup

### PR DESCRIPTION
**Pull request by DerDanilo**
Support setupVars for `pivpnNET`, `subnetClass` and `ALLOWED_IPS` via unattended setup.

- **OpenVPN** --> `pivpnNET` and `subnetClass`
- **Wireguard** --> `pivpnNET`, `subnetClass` and `ALLOWED_IPS`

Fix part of https://github.com/pivpn/pivpn/issues/1273

### CODE REVIEW

**Comment by DerDanilo** [comment]
I am not completely sure that it's early enough to define `subnetClass` in the function `installPiVPN()` since I removed it from the top of the script to have it at the actual place were it can be defined. This makes the check easier if it was pre-defined without the need to add another var.

```
	# Allow custom subnetClass via unattend setupVARs file. Use default if not provided.
	if [ -z "$subnetClass" ]; then
		subnetClass="24"
	fi
```

**Comment by orazioedoardo** [comment]
Can't text the pull request(s) however I can tell that those lines are used to set the static IP settings when using unattended on Raspbian: https://github.com/pivpn/pivpn/pull/1279/files#diff-bb14cdae0728d24ba60e6b112a95f3fd4483e19424969f77308b4954348d5fc8L2-L4

**Comment by DerDanilo** [comment]
> Can't text the pull request(s) however I can tell that [these](https://github.com/pivpn/pivpn/pull/1279/files#diff-bb14cdae0728d24ba60e6b112a95f3fd4483e19424969f77308b4954348d5fc8L2-L4) lines are used to set the static IP settings when using unattended on Raspbian.

What does "Can't text the..." mean?

Are those vars required when setting up wireguard VPN or not? I went through the code and checked all references. They only seem to be required in connection with OpenVPN. So not needed with Wireguard.

**Comment by orazioedoardo** [comment]
> What does "Can't text the..." mean?

Test, actually.

> Are those vars required when setting up wireguard VPN or not? I went through the code and checked all references. They only seem to be required in connection with OpenVPN. So not needed with Wireguard.

Look at [this](https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/auto_install/install.sh#L705) function.

**Comment by DerDanilo** [comment]
Thanks. I checked this function before and could not see why those values should be required by wireguard. 

The genegrated setupVars.conf file does not contain them either. If I understand the `reconfigure=false` flag correctly the script should fail if those vars are required.

I can remove the commit regarding those vars. But I'd like to keep the example files correct if possible.

If I understand those vars correctly they allow to specify the local subnet, including mask and the default gw that the VPN server should use itself? DHCP is not required for Wireguard at all, that is why I am asking.

```
root@v:~# cat /etc/pivpn/wireguard/setupVars.conf
PLAT=Debian
OSCN=buster
USING_UFW=0
IPv4dev=eth0
install_user=wgadmin
install_home=/home/wgadmin
VPN=wireguard
pivpnPORT=1194
pivpnMTU=1280
pivpnDNS1=192.168.25.248
pivpnDNS2=192.168.25.249
pivpnHOST=v.mydomain.com
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=1
pivpnPROTO=udp
pivpnDEV=wg0
pivpnNET=10.10.0.0
subnetClass=24
ALLOWED_IPS="10.10.0.0/24, 192.168.25.0/24"
UNATTUPG=1
INSTALLED_PACKAGES=(iptables-persistent qrencode qrencode iptables-persistent qrencode)
```

**Comment by orazioedoardo** [comment]
> The genegrated setupVars.conf file does not contain them either.

Because you tested the script on Debian, it does on Raspian.

> If I understand those vars correctly they allow to specify the local subnet, including mask and the default gw that the VPN server should use itself?

Yes

Switch target branch to test please.

**Comment by DerDanilo** [comment]
> Because you tested the script on Debian, it does on Raspian.

So if one should use those vars we can leave them in the example file. Maybe we should extend the documentation and explain what those vars are for. 



> Switch target branch to test please.

Done

**Comment by DerDanilo** [comment]
How do we get this merged now? In my test installations it was working fine.

**Comment by 4s3ti** [comment]
Please resolve the conflicts on your base branch please, seems to be related with the merge of one of your merge requests.

**Comment by DerDanilo** [comment]
> Please resolve the conflicts on your base branch please, seems to be related with the merge of one of your merge requests.

Apparently it was caused by the other merge request I pushed. Will check this soon and for it fixed.

**Comment by DerDanilo** [comment]
Sorry for the delay. Was busy and then forgot about it. Hope it's fine now and can get merged soon.

**Pull request merged**
