### PR TITLE
Added support for Linux Mint 19.3

### PR DESCRIPTION
**Pull request by troygeiger**
I wanted to install pivpn onto my Linux Mint installation. Here are the changes I've made to get it to install. I have only tried with the OpenVPN option and haven't tried to uninstall so I cannot confirm that those areas work. I would think so since Linux Mint is based on Ubuntu.

### CODE REVIEW

**Comment by troygeiger** [comment]
Unfortunately not. I hope that they will add support for Pi someday. I know pivpn wasn't ment to be for desktop but it seems to work fine. My Pi died a couple of days ago and I wanted to get my VPN back up and pivpn makes it way easier to setup. I see someone else is also requesting Mint support on issue #1038

**Comment by 4s3ti** [comment]
Sorry ... not accepting this one, for multiple reasons ...

1 - lack of testing ... 
2 - Mint is based on debian so it should give you a warning but it should work anyway. 
3 - We cannot keep up with the releases of every distribution ... so we are sticking with 2 main ones .. ubuntu and debian for now. 
4 - Mint doesn't run on a Pi, support for ubuntu, reason why ubuntu is supported is because it runs also in most inexpensive VPS thus allowing those who want a VPN offshore to have it using pivpn. 
5 - Mint is a desktop distribution therefore not the right place to run a VPN server and would be against our posture of encouraging security and privacy best practices to allow such a thing. 

Once again sorry for refusing but hope you understand. 
Kind regards.

**Comment by orazioedoardo** [comment]
@4s3ti Probably Mint gives a fatal error since it's not "Debian", "Ubuntu", "Raspbian" in the release file. Agree with the rest. At best there could be an argument like `--skip-unsupported` to force proceeding.

**Comment by troygeiger** [comment]
@orazioedoardo There were no errors while installing; at least not for the OpenVPN option. I haven't tried the WireGuard option but that would probably work as well. Mint is based on Ubuntu and uses many of it package repos. All of the pivpn commands have been working without issue.
That being said, I understand the reasoning for not merging this pr. Supporting many distros would be a pain. I do like to idea of a --skip-unsupported though or maybe a --allow-unsupported.

**Comment by Mihaib258** [comment]
Get the based of Linux Mint version you use and add it into the installation file if they are supported, for example for LM 19.3 as following:
	OSCN="bionic"
	PLAT="Ubuntu"
The file here contains this:
[install.sh.zip](https://github.com/pivpn/pivpn/files/4682986/install.sh.zip)
Please be aware not to use his file in other environment!
A better way is to modify the installer by adding "LinuxMint" and "tricia" version all over the file side by side with "Ubuntu" and "bionic".

**Comment by Audioslaver** [comment]
As a user : making a VPN install script in order to simplify the VPN installing process is a neat progress...and definitely "fitted" for desktop distro users that dont want to spend hours.
My experience is that I have it installed on a dedicated machine at home with a Ubuntu LTS installed on it. I dont plan to install a Debian since I dont find it "Out of the box" enough. What I want is to install a distro and use it to do what I have to do with it, not spend hours installing it.
Mint has my preference over Ubuntu and has a significant share in terms of users now, and it would seem relevant for me to make piVPN run on it.
Power users dont need a script to run a VPN. People who are definitely happy to use PiVPN are noobs like I am, who are likely to use a distro like Mint.

**Pull request closed without merging**
