### PR TITLE
Removed the duplicate-cn option so every device/connection must use a unique certificate

### PR DESCRIPTION
**Pull request by jellemdekker**
Removed the duplicate-cn option so every device/connection must use a unique certificate. Please see issue #358 for an in-depth explanation.

### CODE REVIEW

**Comment by redfast00** [comment]
Can you test this PR on a real OpenVPN server with mulitple clients? Lgtm, thanks!

**Comment by jellemdekker** [comment]
Sure thing, will try it tomorrow. :)

**Comment by jellemdekker** [comment]
I've tested it again and it works fine:
- Device A connects successfully with Profile1.ovpn,
- Device B connects successfully with Profile1.ovpn,
- The server terminates device A's connection.

**Comment by redfast00** [comment]
Can you test two devices connecting with a different profile?

**Comment by jellemdekker** [comment]
Just tested it, they can still concurrently connect and stay connected. So devices with different profiles remain unchanged.

**Comment by redfast00** [comment]
Okay, thanks!

**Pull request merged**
