### PR TITLE
Merge test branch

### PR DESCRIPTION
**Pull request by redfast00**

### CODE REVIEW

**Comment by redfast00** [comment]
@Giraffe1966 @orazioedoardo  and probably others: I don't have a lot of time these days, and @0-kaladin, the owner of the organisation doesn't seem to be around anymore. Can you please test if this works? I'd love to give some admin powers to someone else, but I'm just a member

**Comment by Giraffe1966** [comment]
This works for me. I just used the default settings in the installer.

**Comment by orazioedoardo** [comment]
@redfast00 Works for me as well. I tried the alternative options instead.

**Comment by redfast00** [comment]
@Giraffe1966 @orazioedoardo thanks for your time,  will merge this into master

**Pull request merged**
