### PR TITLE
add missing bang to shebang. correct usage of cp. correct wrong copy …

### PR DESCRIPTION
**Pull request by corbolais**
…target dir. safeguard sudo-rm-rf. safeguard against variable expansion into IFS chars. clean up whitespace.

Signed-off-by: corbolais <corbolais@gmail.com>

### CODE REVIEW

**Comment by 4s3ti** [comment]
@corbolais Thanks a lot for this, however i have to Deny this one, 
1 - No changes are pushed directly to master,
2 - We are locking down Master branch as Test has a lot of new code and changes that will after take over the master branch, you should pull that one and push those fixes there if they still exist. 

Once again, sorry for this, and thanks a lot for helping to improve pivpn.

**Comment by orazioedoardo** [comment]
Agree with @4s3ti. @corbolais please make a new pull request using test as reference. Your pull requests overlap too, one is enough for the changes you suggested.

Good point on [this](https://github.com/pivpn/pivpn/pull/874/files#diff-299d9b30c952310aace4aba77c698874L551-R568) and more safeguards, however I'm not a fan of supporting experimental distro releases (the test repo has been tested on debian buster and ubuntu bionic).

**Comment by corbolais** [comment]
fair enough.
my pain.

**Comment by corbolais** [comment]
update.sh got refactored or just removed?

**Comment by corbolais** [comment]
> experimental distro releases

buster isn't really an experimental distro. fact ist, I'd like to use pivpn on bullseye/sid. I provided the required changes to have it so. Why not merge into test then.

**Comment by orazioedoardo** [comment]
> update.sh got refactored or just removed?

Still there, just moved: https://github.com/pivpn/pivpn/blob/test/scripts/openvpn/update.sh

> buster isn't really an experimental distro.

Sorry I meant that the script has not been tested on experimental releases, only on stable releases like buster and bionic.

> fact ist, I'd like to use pivpn on bullseye/sid.

You can still use it, even though the script will tell you that the relase may not work.

> I provided the required changes to have it so. Why not merge into test then.

My rationale is that if we claim that pivpn has been tested on bullseye/sid, we will need to keep testing the script over and over since the repo may introduce breaking changes.

**Comment by corbolais** [comment]
> My rationale is that if we claim that pivpn has been tested on bullseye/sid, we will need to keep testing the script over and over since the repo may introduce breaking changes.

Same once the releases are finalized and out. But then it will be supported from the get go.

**Comment by orazioedoardo** [comment]
> Same once the releases are finalized and out. But then it will be supported from the get go.

We don't regularly check the script (I mean, on a time basis), only when pushing commits to master, considering how many people work on the project as of now.
Regarding the test branch, I've tested it against the releases above (which do not cover all releases from the master branch as I didn't have time these days).

**Pull request closed without merging**
