### PR TITLE
Fix issue pivpn#281

### PR DESCRIPTION
**Pull request by Hir0-84**
Looking for a way to regenerate ovpn after deletion without need for revoking and generating a new certificate for an existing client. It should fix the request https://github.com/pivpn/pivpn/issues/281.

Any suggestions for improvement are welcome.

PS: I have just started using git, I hope I am pulling the request correctly.

### CODE REVIEW

**Comment by orazioedoardo** [comment]
> PS: I have just started using git, I hope I am pulling the request correctly.

Yes you are.

> Any suggestions for improvement are welcome.

I find redundant the usage of two flags `-o` and `-c`. I would just make `-o` available in the `makeOVPN.sh` script.

Main script untouched:

```
pi@raspberrypi:~ $ pivpn -h
::: Control all PiVPN specific functions!
:::
::: Usage: pivpn <command> [option]
:::
::: Commands:
:::  -a, add [nopass]     Create a client ovpn profile, optional nopass
:::  -c, clients          List any connected clients to the server
:::  -d, debug            Start a debugging session if having trouble
:::  -l, list             List all valid and revoked certificates
:::  -r, revoke           Revoke a client ovpn profile
:::  -h, help             Show this help dialog
:::  -u, uninstall        Uninstall PiVPN from your system!
:::  -up, update          Updates PiVPN Scripts
:::  -bk, backup          Backup Openvpn and ovpns dir
```

MakeOVPN script with `-o` and tweaked text (_Regenetate_ instead of _Generate_):
```
pi@raspberrypi:~ $ pivpn -a -h
::: Create a client ovpn profile, optional nopass
:::
::: Usage: pivpn <-a|add> [-n|--name <arg>] [-p|--password <arg>]|[nopass] [-d|--days <number>] [-b|--bitwarden] [-i|--iOS] [-o|--ovpn] [-h|--help]
:::
::: Commands:
:::  [none]               Interactive mode
:::  nopass               Create a client without a password
:::  -n,--name            Name for the Client (default: 'raspberrypi')
:::  -p,--password        Password for the Client (no default)
:::  -d,--days            Expire the certificate after specified number of days (default: 1080)
:::  -b,--bitwarden       Create and save a client through Bitwarden
:::  -i,--iOS             Generate a certificate that leverages iOS keychain
:::  -o,--ovpn            Regenerate a .ovpn config file for an existing client
:::  -h,--help            Show this help dialog
```

**Comment by Hir0-84** [comment]
Ok thanks! I will make the required modification. Should I make another request? How does it work?

PS: I have an older version of your script installed on the raspberry pi which does not have an update option. What is the safer way to update the script without loosing the configurations for the vpn server? At that time it was only based on OpenVPN and I would like to stick with that for the moment.

The scripts seem to be located under /opt/pivpn and they are the one I am modifying for testing purpose. The same scripts are also located under /etc/.pivpn. Are they used? What is the purpose of this directory?

**Comment by orazioedoardo** [comment]
> Ok thanks! I will make the required modification. Should I make another request? How does it work?

Either add additional commits to the `enhancement/issue_no281` of your fork or close this pull request, create a new branch with the modifications make a new one pull requests.

> PS: I have an older version of your script installed on the raspberry pi which does not have an update option. What is the safer way to update the script without loosing the configurations for the vpn server? At that time it was only based on OpenVPN and I would like to stick with that for the moment.
>
> The scripts seem to be located under /opt/pivpn and they are the one I am modifying for testing purpose. The same scripts are also located under /etc/.pivpn. Are they used? What is the purpose of this directory?

This is off topic but read [this](https://github.com/pivpn/pivpn/wiki/Upgrading) and [this](https://github.com/pivpn/pivpn/commit/f06f6d79203c29ebd785f860a81a15e9caac4fc9) regarding updating and [this](https://github.com/pivpn/pivpn/commit/823afa3fbb1199f66782111d9fc41a35c582d015) regarding the multiple scripts locations.

**Comment by Hir0-84** [comment]
Thanks for the info, it is now clear. I have made the modifications, please let me know if it is fine with you!

**Comment by sak171** [comment]
Hm&@** **

**Comment by sak171** [comment]
- Hm&@** jj```
#`@`
```

**Pull request merged**
