### PR TITLE
Merging Test Branch into Master

### PR DESCRIPTION
**Pull request by 4s3ti**
This PR has all conflicts between master and test solved. 
Merges Test Branch into Master. 

If something gets broken ... well .. flame me! =D

### CODE REVIEW

**Comment by 4s3ti** [comment]
@orazioedoardo @james-lasersoft @Giraffe1966 @devZer0 ... looks clean now, Can you just double check before hitting the Merge button? 

Thanks! =)

**Comment by orazioedoardo** [comment]
Looks good to me, except the issue template. Basically I removed the request for the output of iptables and netstat because the debug script does those checks. Should we keep them for redundancy?

**Comment by 4s3ti** [comment]
@orazioedoardo you are right, missed that. if debug script is doing it already I don't think there is a need for it. Will remove that chunk then.

**Comment by 4s3ti** [comment]
Done
Removed the IPTables and netstat lines from issue template. 
Merging test branch into master.

**Pull request merged**
