### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by OfficialMuffin**

### CODE REVIEW

**Comment by OfficialMuffin** [comment]
Apologies if this is incorrect again, I'm still learning git

**Comment by 4s3ti** [comment]
It's fine, don't worry, we all been there :D  let-me guide you without you having to close and re-open. 

Based on your for and branch ... let's do it like this. 

1) make sure you are on your test branch: `git checkout test`
2) reset all commits without losing changes: `git reset --soft 704d9f9`
    * This will reset your commits to the commit id: 704d9f979586e1668af23654e2a4dc2223f2fec0 without loosing the changes you have done on the commits after. 
3) commit your changes with the correct commit message style. 
    * here this is enough: `git commit -m "docs(readme): fix typos"

**Pull request merged**
