### PR TITLE
Some enhanced (rights & telekom hybrid)

### PR DESCRIPTION
**Pull request by LMS235**
right adjustment
- read for "other" withdrawn from .ovpn files
- delete also /etc/openvpn/easy-rsa/pki/${CERTS_TO_REVOKE[ii]}.ovpn after remove certificate

Telekom Hybrid Check 
- Small check whether Telekom Hybrid will be used to give helpful tips.

### CODE REVIEW

**Comment by Giraffe1966** [comment]
This seems related to issue #54 (since Telekom Hybrid uses 4G LTE when DSL is congested), which doesn't just affect Telekom Hybrid. I don't believe checking for this specific router is worth it, because it isn't a Telekom-specific problem, and most users won't be affected. Perhaps an informational dialogue similar to the one you've created could be added to the installer warning about cellular usage in general.

**Comment by LMS235** [comment]
Telekom Hybrid uses both connections simultaneously as a tunnel, hence the smaller MTU value. For normal users in DE there is this as far as I know only from the Telekom so and also only these two routers. Professional users should know what to do anyway.

And the check is only visible if one of the two routers is found. So for 98% of the users it is never visible. But for the other 2% surely helpful.

**Comment by Giraffe1966** [comment]
Maybe at the beginning of the installer a `whiptail` prompt could inform people where to search if they have a problem such as this one. It could direct people to check the wiki pages and then search the issues. This could help everybody that has a problem, including Telekom Hybrid users.

**Comment by LMS235** [comment]
This can certainly be installed in addition. But there is nothing against accepting the current pull-request. Or do I understand that wrong?

**Comment by Giraffe1966** [comment]
I think the info prompt should be for all issues, and `chmod 600` would be more secure for the config files (only allowing owner to read/write). Thanks for catching that permission issue!

**Comment by Giraffe1966** [comment]
@LMS235 Please change the target branch to the test branch.

**Pull request merged**
