### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by OfficialMuffin**

### CODE REVIEW

**Comment by 4s3ti** [comment]
Ty for the PR .. please read and change the target branch: https://github.com/pivpn/pivpn#pull-requests

**Comment by OfficialMuffin** [comment]
Apologies. I'll get that done

**Comment by orazioedoardo** [comment]
Actually it's with capital G.

**Review by 4s3ti — CHANGES_REQUESTED** [review]
`WireGuard` as mentioned by @orazioedoardo 

Please fix the commit message to follow the rules mentioned on the document above. 

Header should be: `docs(readme): fix typo`
the message can be empty in this case.

**Pull request closed without merging**
