### PR TITLE
Feature: Add Index based option for remove/qr commands

### PR DESCRIPTION
**Pull request by gizmocuz**
As we could have many client profiles, each with complex names, I thought it would be great if we could also enter a Index value instead of the profile name for the QR code display and delete option

For example:

:: Client list ::
• [1] HomeRob
• [2] HomeRobMobile
• ....
Please enter the Index/Name of the Client to show:

Where the user can either enter '2', or 'HomeRobMobile

This PR has been tested with OpenVPN/remove and WireGuard remove/qr commands

Previous version displayed a middle-dot at the beginning of each line, but i noticed a printing issue in one of my test systems and decided to remove it.
(It looked better with the dot)

https://github.com/pivpn/pivpn/issues/1086

### CODE REVIEW

**Comment by orazioedoardo** [comment]
I think `1) HomeRob` resembles a list better then `[1] HomeRob`.

**Comment by gizmocuz** [comment]
Made the changes to display it in a better format

**Comment by orazioedoardo** [comment]
> Made the changes to display it in a better format

I see, thanks! Will test later.

**Comment by orazioedoardo** [comment]
As I said [here](https://github.com/pivpn/pivpn/pull/1085#issuecomment-655492023), I think there should be a minimum lenght requirement for names, otherwise:

```
$ pivpn -r
::  Client list  ::
1) test
2) 3
Please enter the Index/Name of the Client to be removed from the list above: 3
:::  does not exist
```

You can't remove client '3' by name because '3' is an index and the code will delete the third client (if it exists).

**Comment by gizmocuz** [comment]
@orazioedoardo , I agree, but that is not related to this patch. We could make another patch for the name requirements.
I also think you should enter a good name, not 1,2,3, we're asking to enter a name, not a number.
It is also very bad practice to name things 1,2,3 instead of RemoteMobile, RemoteLaptop, Remote....

**Comment by orazioedoardo** [comment]
Sure, '3' is not a good name, however I think for correctness the code should handle those cases, for example require minimum length of 4 so 1111 is definitely a name (you can't have more than 253 clients).

I think it's related to this patch because technically you could remove a client named '3' and now you can't in certain cases. However I'm going to make some changes to the test branch so maybe I can do that myself.

**Pull request merged**
