### PR TITLE
Merging Master into Test

### PR DESCRIPTION
**Pull request by 4s3ti**
Merging master branch into the test branch, to reflect all the changes made directly to master branch. 
resolved all the conflicts.

### CODE REVIEW

**Comment by 4s3ti** [comment]
@orazioedoardo some of your comments are landing here, can you please also take a look and double check if everything seems ok? 

I could have missed something.

**Comment by 4s3ti** [comment]
not approving ... tested it definitely takes pieces of code that break it... will investigate.

**Comment by orazioedoardo** [comment]
@4s3ti Basically you undid all changes with this commit: https://github.com/pivpn/pivpn/pull/735/commits/ab429de9250570427d933aba8dca96eaaf847e67

**Comment by 4s3ti** [comment]
Thats why i am not merging it... something looking confusing to me here.. so i'd rather sit with a bit more time and look properly to what happened in the meantime

**Comment by orazioedoardo** [comment]
Can I open a pull request like this one https://github.com/pivpn/pivpn/pull/734 and try to fix the conflicts?

**Comment by 4s3ti** [comment]
@orazioedoardo I will do it today .. but feel free.. if yours lands here faster then I make the merge.

**Pull request closed without merging**
