### PR TITLE
Adding support for custom search domain

### PR DESCRIPTION
**Pull request by quwip10**
Main changes:

  This code creates a new setCustomDomain() procedure to allow users the option to add a custom search domain during install.

It also adds a function valid_domain() that uses regex to do a mild validation on domain input.

This code will then insert into the created server.conf

### CODE REVIEW

**Comment by Giraffe1966** [comment]
@quwip10 pivpn is designed to make it as simple as possible to set up a VPN. I'm afraid adding a custom search domain might make things more confusing for inexperienced users. However, only one line has to be changed to add a custom search domain, so it is really easy to add one yourself if you need one.

**Comment by Giraffe1966** [comment]
@quwip10 Please change the target branch to the test branch, so it can be tested first.

**Comment by quwip10** [comment]
I think PiVPN can be useful for all sorts of users rather than just beginners. The custom search domain can often be used with the custom DNS option which is already supported. I also hid the feature behind a warning that it is for advanced users. Pull request added to the test fork although that fork is pretty far behind master.

**Comment by Giraffe1966** [comment]
I've submitted a PR to update the test branch.

**Comment by Giraffe1966** [comment]
@quwip10 I like the idea of adding more advanced features, but only if they are hidden behind advanced feature warnings, like you've suggested. Perhaps pivpn should have an advanced features mode, where more configuration is possible.

**Comment by quwip10** [comment]
@Giraffe1966 I agree. I like the idea of an advanced mode also. I considered coding it, but wanted to get this update in first.

**Comment by Giraffe1966** [comment]
@quwip10 I think this should be closed now, as #706, the PR I believe you intended to merge, has been merged.

**Pull request closed without merging**
