### PR TITLE
Unattended installation

### PR DESCRIPTION
**Pull request by orazioedoardo**
Changes:
1) Added back unattended installation: as expected, the user can call the install script with `--unattended` followed by a config file and PiVPN will be installed non-interactively. Two examples are provided in case the user wants to customize every setting. However you don't need to specify all of them, missing one are filled with defaults IF those settings can be detected unambiguously. For example if you only have one user and one network interface the script proceeds, however if you have several of them it does not.
2) Removed `persist-key` and `persist-tun` from the client config.
3) Reverted `keepalive` setting on the server to smaller values.
See @TinCanTech's posts for the reasons of the above two: https://github.com/pivpn/pivpn/issues/864#issuecomment-553496345
4) Copied `validDomain()` function from the test branch.
5) Removed 1024 bit certificate options, since on Buster OpenVPN does not start with such small certificates (I think it's related to OpenSSL 1.1.1).
6) Backup `/etc/openvpn` and `/etc/wireguard` before installing.
7) Always remove VPN configuration when uninstalling, but do not wipe the folder, just remove what PiVPN added.
8) Fetch latest WireGuard snapshot instead of hardcoding it into the script.

### CODE REVIEW

**Comment by 4s3ti** [comment]
@orazioedoardo  
jeeez man .. you have been doing such a great job!! wish i could add you as maintainer here =/ ...
unfortunately didn't had much time to test your new branch ... 

Just tell me one thing , do you feel that this ready to become main test branch? 

I am currently working on the website changes ... git a new domain for pivpn and doing some restructuring on my servers after that the website will be hosted there on a docker container.

**Comment by orazioedoardo** [comment]
> jeeez man .. you have been doing such a great job!! wish i could add you as maintainer here =/ ...

Probably we should ask @james-lasersoft 
> Just tell me one thing , do you feel that this ready to become main test branch?

Not yet, wait for another pull request as I want to add official Ubuntu 18.04 support as well as testing the latest commits on Raspbian, although I think we will have the ultimate test by merging it to the branch.

> I am currently working on the website changes ... got a new domain for pivpn and doing some restructuring on my servers after that the website will be hosted there on a docker container.

Nice! Could be a good time to update the README too.

**Comment by james-lasersoft** [comment]
@4s3ti  @orazioedoardo I invited you as a member of the project team just now and I also have access to the original pivpn.io website.

I also own the domains pivpn.org and pivpn.info if you would like to setup redirects to the pivpn.io domain.

**Comment by 4s3ti** [comment]
Look who's around!! =D @james-lasersoft been trying to reach you out a couple of times ... and it has been hard to do so ... can I get another way of contacting you? email or so?

you can get back to me at 4s3ti@protonmail.com

I also have access to the website code and i can accept merge requests to it. 
I am working on putting it in a docker container to serve it outside of Github and have SSL on it.

**Comment by orazioedoardo** [comment]
Just joined and pushed a small commit.

**Pull request merged**
