### PR TITLE
 General fixes and improvements

### PR DESCRIPTION
**Pull request by orazioedoardo**
Main changes:
- `pivpn debug` now shows a snipped of the log and performs some rudimentary checks against common problems (missing firewall rules, openvpn not starting/listening).
- Change whiptail dialogs from "RSA/ECDSA encryption strength" to "RSA/ECDSA certificate size" since RSA/ECDSA is not used for encryption but for authentication (README was updated accordingly).
- Removed unused `firewall-openvpn-rules.txt` and `ca_info.txt`, replaced `ufw_add.txt` with a one-liner, `fix_iptables.sh` was incorporated into `pivpnDebug.sh`.
- If any of the functions invoked by `installPiVPN` runs `exit somecode` the script would not actually exit since `installPiVPN` is piped into `tee ${tmpLog}`, giving the impression that the script succeded. I removed the piping for this reason (the install log didn't provide much information anyways).
- Stricter firewall rule: when using UFW, do not set the FORWARD policy to ACCEPT to allow everything, instead, only forward traffic coming from the VPN interface.

### CODE REVIEW

**Comment by Giraffe1966** [comment]
@orazioedoardo Perhaps it would be better to merge this into the test branch first, since that is what CONTRIBUTING.md suggests.

**Comment by james-lasersoft** [comment]
I agree with this, please swap to the test branch.

**Comment by orazioedoardo** [comment]
@Giraffe1966 @james-lasersoft Ok, done.

**Comment by james-lasersoft** [comment]
@orazioedoardo, I see that some of the proposed updates have already been merged. Would you mind resolving the conflicts so I can push the merge?

**Comment by orazioedoardo** [comment]
@james-lasersoft A bit late but I resolved the changes.

**Pull request merged**
