### PR TITLE
Code cleanup + WireGuard support

### PR DESCRIPTION
**Pull request by orazioedoardo**
This pull requests attempts to clean up the install script and its control flow. Unfortunately, the diff is significantly bloated due to the fact that I recreated the script from a new file, moved functions to match their order of execution and used a different indentation in my editor, so i suggest you just look at the individual file [here](https://github.com/orazioedoardo/pivpn/blob/test-wireguard/auto_install/install.sh).

Some function had been split, for example `installDependentPackages` into `installDependentPackages` and `preconfigurePackages` such that the first function can be reused without reapplying the settings in the second function.

Other function have been slimmed down, for example functions that ask the user for the port, protocol, dns, domain don't actually apply the setting, they only save the variable on disk. This way they can be reused for WireGuard too (which actually is the only new feature), the settings are being applied in relevant functions like `confOpenVPN`, `confOVPN`, `confWireGuard`. WireGuard is now the default choise while providing OpenVPN as an alternative (in the `askWhichVPN` function).

WireGuard is installed from a debian package on armv7l Raspberry Pis and x86_64/i686 Debian, wheres is compiled and installed via DKMS on older, armv6l Raspberry Pi (see [here](https://lists.zx2c4.com/pipermail/wireguard/2017-November/001885.html) for the reason).

A dedicated apt settings avoids pulling packages form the unstable repo other than wireguard itself. On Debian, this uses the provided file `unstable.list` from the wireguard website which sets a priority of the package lower than all the other packages in the stable repo. On Raspbian i had to create a different one since i saw that the official one prevented apt updates/upgrades, this one blacklist everything except wireguard.

Variable used during the installation are now all inside the `/etc/pivpn/setupVars.conf`, for simplicity. Here's two examples from both wireguard and openvpn installations:
```
PLAT=Debian
OSCN=buster
IPv4dev=ens3
IPv4addr=192.168.1.2
IPv4gw=192.168.1.1
install_user=user
install_home=/home/user
VPN=OpenVPN
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnHOST=0.0.0.0
pivpnENCRYPT=2048
DOWNLOAD_DH_PARAM=1
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
USING_UFW=0
UNATTUPG=1
```
```
PLAT=Raspbian
OSCN=buster
IPv4dev=eth0
IPv4addr=192.168.1.3
IPv4gw=192.168.1.1
install_user=pi
install_home=/home/pi
VPN=WireGuard
pivpnPORT=2345
pivpnDNS1=8.8.8.8
pivpnDNS2=8.8.4.4
pivpnHOST=0.0.0.0
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
USING_UFW=0
UNATTUPG=1
```
This pull request is not complete, in fact it misses:
- uninstallation
- unattended install
- support for platforms other than Rasbpian/Debian 10, which are the only ones i have tested
- reconfigure
- update (actually now i'm seeing that there is a dedicated script `update.sh` pulls the latest scripts from git)

I don't expect this to merge as of now, but I'm opening it to get some feedback on whether i should continue with this work.

To test, download the script and run `TESTING=test-wireguard ./install.sh`.

### CODE REVIEW

**Comment by 4s3ti** [comment]
I havent reviewed it .. but since this is a test branch for this sole purpose ill approve and merge it and test and check it latter when i have time for it =)

**Comment by orazioedoardo** [comment]
I'll continue working on the script but I'll wait for you to review it before sending additional pull requests, @4s3ti what do you think?

**Comment by 4s3ti** [comment]
@orazioedoardo feel free to keep doing your magic! =) i can check it all later on, you've been quite a great contributor so that's just fine for me if you keep making PRs

**Comment by orazioedoardo** [comment]
@4s3ti Thank you! I'm not going to spam pull requests that are hard to keep track of, though. I'll bundle up several commits before sending.

https://github.com/pivpn/pivpn/issues/844,

**Pull request merged**
