### PR TITLE
AES Encryption instead of 3DES

### PR DESCRIPTION
**Pull request by Zeik0s**
I was wondering why in the script the encryption method 3DES is used. This algorithm is long outdated and deprecated. By simply choosing the AES with 128 bits key length the saved key would be safer for being brute-forced. Therefore it would be a security bonus without changing much.

### CODE REVIEW

**Comment by InnovativeInventor** [comment]
This sounds like a no-brainer, I like this!

**Comment by redfast00** [comment]
First off, thanks for contributing! I think we were using 3DES for compatibility with iPhones or something. A quick seach through the open issues found https://github.com/pivpn/pivpn/issues/171.

**Comment by orazioedoardo** [comment]
@redfast00 AES128 works fine with iPhones (AES256 works too).

**Comment by redfast00** [comment]
@orazioedoardo thanks. I can now merge this, but this PR contains a lot of unrelated commits and I don't think it's been tested yet. Any input @cfcolaco ?

**Comment by cfcolaco** [comment]
@redfast00 think this PR is actually cool ... will merge into test all commits ahead of Test branch! so should be fairly safe to commit! =)

**Comment by trilleplay** [comment]
so are we merging this, i'm all for it

**Pull request merged**
