### PR TITLE
Script for ovpn file conversion for the "OpenVPN Connect" app (iOS+Android)

### PR DESCRIPTION
**Pull request by TimmThaler**
Based on the [issue 364](https://github.com/pivpn/pivpn/issues/364) I created a script that does convert the original ovpn file of a client from an rsa to aes256 key so that it will be usable with both the iOS and Android app "OpenVPN Connect".

I would appreciate some testing. 👍 

Edit: Script needs to be run as sudo

### CODE REVIEW

**Comment by TimmThaler** [comment]
Just updated the script so that all clients are shown now. There was a wrong variable name... I also added an exit point when no client is chosen.

Any testing and feedback is welcome 😃

**Comment by TimmThaler** [comment]
While this is an issue for both the iOS and the Android app "OpenVPN Connect" I changed the script name and the descriptions.

**Comment by justinamcafee** [comment]
Is this pull still needed? I show that OpenVPN connect updated to 3.0 around Feb/Mar 18 and that the conversion to aes256 is no longer necessary.

**Comment by cfcolaco** [comment]
@justinamcafee yup think this pull isn't needed anymore and never agreed with providing such a feature, anyway. 

@redfast00 closing this one, please tell me if anything wrong with it.

**Pull request closed without merging**
